//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR9Kile.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RussianPsychologicalSocietyEntities1 : DbContext
    {
        private static RussianPsychologicalSocietyEntities1 _context;
        public RussianPsychologicalSocietyEntities1()
            : base("name=RussianPsychologicalSocietyEntities1")
        {
        }

        public static RussianPsychologicalSocietyEntities1 GetContext()
        {
            if (_context == null)
                _context = new RussianPsychologicalSocietyEntities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomersTable> CustomersTable { get; set; }
        public virtual DbSet<PsychologistTable> PsychologistTable { get; set; }
        public virtual DbSet<TypeTable> TypeTable { get; set; }
    }
}
