//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR9Kile.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsychologistTable
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Type { get; set; }
        public int Cabinet { get; set; }
    
        public virtual TypeTable TypeTable { get; set; }
    }
}
